[package]
name = "websocket-server"
version = "0.1.0"
authors = ["Jan Nils Ferner <jn_ferner@hotmail.de>"]

[dependencies]
futures = "0.1"
futures-cpupool = "0.1"
tokio-core = "0.1"

[dependencies.websocket]
features = ["nightly"]
version = "0.20"
